// <auto-generated />
using System;
using CalendarApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalendarApi.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGroupMeeting")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Appointments");

                    b.HasDiscriminator<bool>("IsGroupMeeting").HasValue(false);

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            EndTime = new DateTime(2026, 5, 6, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Phòng A1",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Họp Sprint Planning"
                        },
                        new
                        {
                            AppointmentId = 2,
                            EndTime = new DateTime(2026, 5, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Nhà hàng Hải Sản",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 6, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ăn trưa với khách"
                        },
                        new
                        {
                            AppointmentId = 3,
                            EndTime = new DateTime(2026, 5, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Online",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Review code"
                        },
                        new
                        {
                            AppointmentId = 4,
                            EndTime = new DateTime(2026, 5, 7, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Phòng gym tầng 2",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tập gym"
                        },
                        new
                        {
                            AppointmentId = 5,
                            EndTime = new DateTime(2026, 5, 8, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Thư viện",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Đọc tài liệu OOAD"
                        },
                        new
                        {
                            AppointmentId = 6,
                            EndTime = new DateTime(2026, 5, 6, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Online",
                            OwnerId = 2,
                            StartTime = new DateTime(2026, 5, 6, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Học tiếng Anh"
                        },
                        new
                        {
                            AppointmentId = 7,
                            EndTime = new DateTime(2026, 5, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Quán cà phê",
                            OwnerId = 2,
                            StartTime = new DateTime(2026, 5, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gặp mentor"
                        },
                        new
                        {
                            AppointmentId = 8,
                            EndTime = new DateTime(2026, 5, 7, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Công viên",
                            OwnerId = 3,
                            StartTime = new DateTime(2026, 5, 7, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chạy bộ buổi sáng"
                        },
                        new
                        {
                            AppointmentId = 9,
                            EndTime = new DateTime(2026, 5, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = false,
                            Location = "Nhà",
                            OwnerId = 3,
                            StartTime = new DateTime(2026, 5, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nấu ăn"
                        });
                });

            modelBuilder.Entity("CalendarApi.Models.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReminderId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Reminders");

                    b.HasData(
                        new
                        {
                            ReminderId = 1,
                            AppointmentId = 1,
                            Method = "POPUP",
                            RemindAt = new DateTime(2026, 5, 6, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReminderId = 2,
                            AppointmentId = 3,
                            Method = "EMAIL",
                            RemindAt = new DateTime(2026, 5, 7, 13, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReminderId = 3,
                            AppointmentId = 10,
                            Method = "POPUP",
                            RemindAt = new DateTime(2026, 5, 9, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CalendarApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Toàn"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Sơn"
                        },
                        new
                        {
                            UserId = 3,
                            FullName = "Dũng"
                        });
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants", (string)null);

                    b.HasData(
                        new
                        {
                            AppointmentId = 10,
                            UserId = 1
                        },
                        new
                        {
                            AppointmentId = 11,
                            UserId = 1
                        },
                        new
                        {
                            AppointmentId = 12,
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 13,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CalendarApi.Models.GroupMeeting", b =>
                {
                    b.HasBaseType("CalendarApi.Models.Appointment");

                    b.HasDiscriminator().HasValue(true);

                    b.HasData(
                        new
                        {
                            AppointmentId = 10,
                            EndTime = new DateTime(2026, 5, 9, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = true,
                            Location = "Phòng Lab",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Họp nhóm đồ án"
                        },
                        new
                        {
                            AppointmentId = 11,
                            EndTime = new DateTime(2026, 5, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = true,
                            Location = "Phòng A2",
                            OwnerId = 1,
                            StartTime = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thảo luận báo cáo"
                        },
                        new
                        {
                            AppointmentId = 12,
                            EndTime = new DateTime(2026, 5, 9, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = true,
                            Location = "Phòng Lab",
                            OwnerId = 2,
                            StartTime = new DateTime(2026, 5, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Họp nhóm đồ án"
                        },
                        new
                        {
                            AppointmentId = 13,
                            EndTime = new DateTime(2026, 5, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsGroupMeeting = true,
                            Location = "Online",
                            OwnerId = 3,
                            StartTime = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thảo luận báo cáo"
                        });
                });

            modelBuilder.Entity("CalendarApi.Models.Appointment", b =>
                {
                    b.HasOne("CalendarApi.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CalendarApi.Models.Reminder", b =>
                {
                    b.HasOne("CalendarApi.Models.Appointment", null)
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.HasOne("CalendarApi.Models.GroupMeeting", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalendarApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CalendarApi.Models.Appointment", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
